#!/bin/env bash

cargo-web deploy &&\
sed -i "s/localhost/66.42.96.214/g" target/deploy/env.js &&\
aws s3 sync --profile 586-deployer target/deploy s3://586-frontend &&\
aws s3 cp --profile 586-deployer --content-type 'application/wasm' s3://586-frontend/frontend.wasm s3://586-frontend/frontend.wasm --metadata-directive REPLACE
